apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-platform
  template:
    metadata:
      labels:
        app: shopping-platform
    spec:
      containers:
        - name: shopping-platform
          image: ghcr.io/amanbharti01/shopping-platform:e12146ac4fb2f34f0d2305f7e860adcc98f0e06a
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
