apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-platform
  template:
    metadata:
      labels:
        app: shopping-platform
    spec:
      containers:
        - name: shopping-platform
          image: ghcr.io/amanbharti01/shopping-platform:0fd3b21de12d8298cf9d634a37cce780323e6113
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
