apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-platform
  template:
    metadata:
      labels:
        app: shopping-platform
    spec:
      containers:
        - name: shopping-platform
          image: ghcr.io/amanbharti01/shopping-platform:652d582bc9cbefd87c1882bf727c0d24470eefb9
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
